[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# Etherscan / Block Explorer API Keys
# Get your API key from https://etherscan.io/myapikey
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }

[rpc_endpoints]
sepolia = "${RPC_URL}"
